Test user authentication with Cypres
makeitrealcamp/top-v18 pull request #14
Opened 2022-01-21 02:22 UTC by augfor

### Descripción
Test para probar la autenticación de los usuarios implementando Cypress.

### Feeling
[//]: <> (Como te sientes con este PR? la solucion que entregas como te hace sentir?)
- [ ] 🤙 Solucion rapida
- [ X ] 👌 Terminado y listo
- [ ] 🤞 Espero que esto funcione, por favor revisar cuidadosamente

### Tickets
[//]: <> (El numero del ticket asociado a este PR)

### Cómo probar?
[//]: <> (Pasos necesarios para probar esta funcionalidad)

### Screenshots (si es aplicable)
[//]: <> (Capturas de pantalla que ayuden a entender que hiciste en este PR)

### Scope

- [ ] 🐞 Bugfix (non-breaking changes que resuelve un problema
- [ X ] 💚 Mejora (non-breaking change que agrega/modifica funcionalidad a una característica existente)
- [ ] ⚡️ Nueva característica/feature (non-breaking change que agrega una nueva característica)
- [ ] ⚠️ Breaking change (cambio que no es compatible con versiones anteriores y/o cambia la funcionalidad actual)

2022-01-26 18:57 UTC, buty619 requested changes

2022-01-26 18:57 UTC, buty619 commented on projects/react-twitter/cypress/integration/3-twitter/authentication.spec.js
> +describe("user authentication", () => {
muchachos porfa adjunten un pantallazo de CYPRESS con el test OK, gracias ¡¡

2022-01-27 02:01 UTC, augfor commented on projects/react-twitter/cypress/integration/3-twitter/authentication.spec.js
> +describe("user authentication", () => {
Listo! Aquí va...

![Cypress Test](https://user-images.githubusercontent.com/92948594/151278336-d1bfa69b-8d20-4fa2-8d8b-6ae072a459b2.jpg)

2022-01-27 21:02 UTC, buty619 approved these changes

2022-02-01 15:02 UTC, merged